### ISSUE TITLE
Export calculator image

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#1202]
Add a way to export the images from standalone calculators to a file in some format...

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/36214134-a82ead14-1176-11e8-9347-9190fd7f445b.png)
A good start but it needs axis labels and numbers.  

After playing with it a bit, if you wave your mouse over the graph, and then save it, it will "print" properly.  but that seems like more work than should be required of the user 
However, if you do that, its "file type"  is "file" and nothing can open it by default (it can be opened in paint).

We also need to work out how to make a legend on some of the graphs (some don't need or kind of already have them). 

![image](https://user-images.githubusercontent.com/25389736/36214552-c195fab8-1177-11e8-91ea-0ca3c5623a1b.png)
This one behaved.  (although the background is transparent instead of white, which can cause some problems (maybe the legend be in a white box).

**Comment by koay9f** [comment]
Still does not have the file extension on it when saving.  They look good though
- O2 enrichment

Preassessement is okay
