### ISSUE TITLE
PHAST - Design/Metered

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1794]
Instead of unique pages for Design & Metered for the Assessment, add the non-exclusive button to each one, and have it set to the appropriate option for the assessment type

**Comment by koay9f** [comment]
Looking at it in electrotechnology (where result unit is in kW)
Design
Had it set up to be 293.07 kW x 3 (~ 1 MMBtu).  

Steam works  ("contributes" 293.07 kW)
Electricity works ("contributes" 293.07 kW)

Fuel doesn't ("contributes" 1 kW (input is 1 mmbtu))

Metered
Doesn't have units, dropdowns, blue links or math working
Producing an error.
This does not happen if have a new assessment
In new assessment, it has the same error as design (fuel is only contributing 1 kW instead of 1 mmbtu (293.07 kW))

Design works in Fuel Assessments
Metered has the same problem with fuel if using kWh as energy result unit
Steam Assessments are the same as fuel (kWh does not work right)

[design-metered-test.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46ec91892a858de482ecab46b658f4d93d4334676b48e13b628ae92dbc56395b4d5a47f8140a0e46a8f08e7af0e46e708a590cbbd0680c26c02f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e583874e3f18051b89f65d27ed.txt)
