### ISSUE TITLE
Flow Calculations Energy Use - Calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#192]
Calculator only for fuel fired furnace

![image](https://cloud.githubusercontent.com/assets/8973004/25197754/0efa9f72-2513-11e7-98e9-de4e4bb6698c.png)

**Comment by gaccawi** [comment]
Gas types in PHAST 3:

![image](https://cloud.githubusercontent.com/assets/8973004/25197825/639b94d2-2513-11e7-8bb4-c8b459bf640c.png)
![image](https://cloud.githubusercontent.com/assets/8973004/25197831/670a4802-2513-11e7-9a77-84326f38323d.png)

**Comment by gaccawi** [comment]
Type of sections from PHAST 3:
![image](https://cloud.githubusercontent.com/assets/8973004/25197851/7b004992-2513-11e7-9792-0cb28c897dd2.png)

**Comment by koay9f** [comment]
Not to be a pain, but did it get noted that if you put in zero for "Heating Value of Gas" then the calculator changes to calculating "Total Flow" instead of Energy Use?  Just noticed this while working on help text.
![flow calculator](https://user-images.githubusercontent.com/25389736/27966487-687b6eae-630d-11e7-9b2b-a8003497f1fb.png)

**Comment by gaccawi** [comment]
So, in the calculations, if the heating value of the gas is <= 0, the heatInput is actually the total flow. So, they are correct.
However, when coding the user interface, the label needs to change.

Alternately, we could have an additional field returned/calculated that would be the total flow. This is better than misusing the same return value to represent completely different things.
