### ISSUE TITLE
FSAT/PSAT Warnings vs Errors

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2282]

**Comment by rmroot** [comment]
**Fan things I noticed:

There currently is no warning for:
inlet pressure < outlet pressure warning

Our current warning for fan speed is:
 0 <=  fan speed < =5000 
that doesn't match help text

**Should these be marking the inputs as invalid instead of just warnings:

Motor (Both PSAT/FSAT):
  0 <= specified efficiency <= 100

Field Data (PSAT):
0 <= cost/hr <= 1 
0 <= size margin <= 100
0 <= operating fraction <= 1
0 <= head

Field Data (FSAT)
0 <= specific heat ratio
0 <= outlet pressure
0 <= compressibillity factor
0 <= operating fraction <= 1
0 <= cost/hr <= 1

Fan Setup (FSAT)
0 < = specified efficiency <= 100


Pump Fluid (PSAT)
0 <= specified efficiency <= 100

Fan Fluid (FSAT)
0 < gas density
0 < specific heat gas
0 <= relative humidity <= 100

help
min < val must be in range < max

**Comment by rmroot** [comment]
I think that having some of these being errors (meaning that it won't calculate if out of range) would help prevent some of the wacky results.

**Comment by rmroot** [comment]
Should also consider wording on alot of the messaging. "Should be.." vs "Must be..."

**Comment by koay9f** [comment]
Fans:
inlet pressure > outlet pressure warning
That shouldn't be necessary, but these two would be:
if Fan Inlet Pressure > 0
`Fan Inlet pressure must be less than zero`
if Fan Outlet Pressure < 0
`Fan Outlet Pressure must be greater than zero`



Our current warning for fan speed is:
 0 <=  fan speed < =5000 
yeah, it should probably match the help text. 
the belt drives should just be greater than zero.
Can you add something such that any of the rpm's cannot have a decimal?
`xxx speed must be a whole number`

**Should these be marking the inputs as invalid instead of just warnings: - YES

Motor (Both PSAT/FSAT):
  0 <= specified efficiency <= 100

Field Data (PSAT):
0 <= cost/hr
0 <= size margin
0 <= operating fraction <= 1
0 <= head

Field Data (FSAT)
0 <= specific heat ratio
0 <= outlet pressure
0 <= compressibillity factor
0 <= operating fraction <= 1
0 <= cost/hr

Fan Setup (FSAT)
0 < = specified efficiency <= 100


Pump Fluid (PSAT)
0 <= specified efficiency <= 100

Fan Fluid (FSAT)
0 < gas density
0 < specific heat gas
0 <= relative humidity <= 100

Other places to add invalid entries (and warnings if not there)
any length/width should not be able to be less than zero
any flow rate should not be able to be less than zero
any voltage, current or power should not be able to be less than zero


help
min < val must be in range < max - probably not anywhere else (unless one of the above instances).  we want the users to be able to model some "out there things"

**Comment by koay9f** [comment]
I guess for any that we stop calculations for, change the warning text to "MUST BE" and maybe make the warning/highlight color be red

**Comment by rmroot** [comment]
Check the warning for Barometric Pressure. It is triggering when it shouldn't. What is the warning right now? Should probably just delete it... (changing the units for Pressure Measurement seem to be effecting in. It should be governed by Barometric Pressure Measurement.

-per #2480

**Comment by koay9f** [comment]
For fans in general I think, when the unit system is "custom" it runs through the "else" branch and the ranges are then incorrect.  It probably was effecting more than just Barometric pressure, that was just the only one that was triggered

**Comment by koay9f** [comment]
Barometric Pressure is still giving a warning when in custom units.  (it is saying value should be greater than 65 in Hg...)
Maybe just remove this warning.  The only limit on barometric pressure is that it should be greater than zero.
