### ISSUE TITLE
Specified Pump Type

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2344]
Add support for specified pump efficiency.

**Comment by rmroot** [comment]
Will need suite support as well

**Comment by rmroot** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/268

**Comment by koay9f** [comment]
We already have a specified pump type.
The problem is that it is
1- only an option for modifications (b/c it would not do anything to BL)
2 - not obvious

Solution ideas:
In explore opps, 
a - put specified at top of list for pump types
b- make its own checkbox that overrides pump type?

Something similar in modify all?  or would training/expertise take care of it?
