### ISSUE TITLE
SSMT Sankey

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2353]

**Comment by rmroot** [comment]
![Sankey.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46db959428879aebc3abaf51ab57f5973d047d317c5da72e7284b12ce6157a070d0d4eac445f0945f9aadb2db4aa2e32db025fb28c341521842f1bbeb98a15be04b9278a468cb7b9884ac0ea2f68.png)

**Comment by rmroot** [comment]
Per Kristina's mockup:
"Replace with Sankey?
Do the line size show Flow or loss? Both?
Need to figure out how this works"

**Comment by koay9f** [comment]
[Sankey.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46db959428879aebc3abaf51ab57f5973d047d317c5da72e7284b12ce6157a070d0d4eac445f0945f9aadb2db4aa2e32db025fb28c341521842f1bbeb98a15be04bf22884e80beb9884cc5eb2f68.pdf)

Most arrows use the same numbers as Waterfall graph.  "Returned Condensate" - I will get you the math for.
Input Energy - may be easier to calculate from losses? just so it all lines up?
Need to brainstorm how to do colors?

**Comment by nbintertech** [comment]
Current state of this issue: 3-5 points dev effort. The sankey has been implemented in Plotly with maybe 75% of the energy flows, but still requires work for the circular energy flow, style and logic tweaks.

**Comment by koay9f** [comment]
Most of the time it is looking good, but a few big issues still

When you first make an assessment there is no sankey. You have to exit the assessment then return.

AT4 - turbine + LP vented steam

It looks like the LP vented steam is not being correctly attributed to "other Losses". 
Maybe instead of having the "Remaining Energy" category (since it seems to be causing issues) have anything "remaining" go under "Other Losses"
Also, there is a chunk that is "unaccounted for" (circled in the pic).  I can see this being part of the "remaining energy" problem, but it could be tied with the return condensate. 

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a8a9fa69-05dc-49a6-9c33-13f744438491)[https://app.zenhub.com/files/80439269/33962cc9-af07-4f30-8fdb-edaa88f087d2/download](https://app.zenhub.com/files/80439269/33962cc9-af07-4f30-8fdb-edaa88f087d2/download)
