### ISSUE TITLE
SSMT Losses Calculations

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2624]

**Comment by rmroot** [comment]
![losses-1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e49b89308790e4deabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb60bbb258f4983b7b98948c1ed3e22f5c6.PNG)
![losses-2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e49b89308790e4ddabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4983b7b98948c4e83f2cf5c6.PNG)

**Comment by koay9f** [comment]
Process losses are still off.  

`   calculateProcessLoss(processSteam: ProcessSteamUsage, condensate: SteamPropertiesOutput, settings): number {
    let energy: number = this.calculateEnergy(condensate.massFlow, condensate.specificEnthalpy, settings)
    energy = this.convertUnitsService.value(energy).from('MJ').to(settings.steamEnergyMeasurement);
    let loss: number = (processSteam.energyFlow - (energy) - processSteam.processUsage);
    return loss;
  }`
[line 138-142of  ssmt/ssmt-calculations/calculate-losses.service.ts]

Possible Problems
1 - using the wrong "condensate" properties maybe?
It should be using the "initial XP Condensate" values  
If it helps: instead of "condensate" could run the "saturated steam" properties at the header pressure and take the liquid Enthalpy value, but that is probably more complicated (mass flow would be process usage * (recovery %) )

2- Unit conversion.  Are the other values in the correct units? 
   Looking at `calculateEnergy` massFlow and specificEnthalpy are correct.   
    And then it gets converted to MJ, which is correct. 
    Are the energyFlow & processUsage in MJ?
