### ISSUE TITLE
TH - Print Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3042]
Need to add printing to Treasure hunt report

**Comment by koay9f** [comment]
It works, and I think all the components are there, some formatting issues:

* page 3 - Executive Summary: weird lines by title
* page 3 - Executive Summary: "Detailed Summary" table cut off on left
* page 4 - Report Graphs: Can we get current & projected cost status to be side-by-side?
* page 5 - blank
* through out, something weird going on with lower case L's and upper case I's, but I think it may just be my display
* page 7 - Identified Opportunity: change name to "Payback Details"
* page 7 - Identified Opportunity: graphs overlapping and cut off, maybe stack instead of side by side?
* page 7 - Identified Opportunity: bit of space between title and table?  actually, maybe graphs first, then table?
[https://app.zenhub.com/files/80439269/f9410836-7dd2-4fb5-a55c-5ef4a7f71650/download](https://app.zenhub.com/files/80439269/f9410836-7dd2-4fb5-a55c-5ef4a7f71650/download)

**Comment by koay9f** [comment]
FYI - this is using the TH Example
page 3 - executive summary: "Detailed Summary" still cut off
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/de5efa8d-f580-4c83-8a07-032c742bd5f0)

**Comment by DmitryHoward** [comment]
we will round costs in detailed summary table
