### ISSUE TITLE
Explore Opps + Report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3635]
Need to report which “Assessment” modifications are checked, and echo the input parameters for each modification, i.e. “Install VFD”, “more efficient fan”, etc. - koa - @rmroot can we do this? what about assessments made in expert view? if we do it here we should do with with other assessments also

Could we use something like the Select Scenario page + the checkboxes from Explore Opps?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5c27240a-97e2-4462-ae00-4e4ec7590e86)

**Comment by nbintertech** [comment]
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/49ddcabc-fe8e-419b-9842-314e35c2671b)

![image (1).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/7df42f62-2266-4701-a362-8b3059d33ea6)

Mockups from Kristina. Process heating should be placed in "executive summary" instead of "result data"
