### ISSUE TITLE
Savings for modifications should be calculated relative to Baseline

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#381]
If you use the same input data values for Baseline and Modification 1, the tool gives the same “Annual Savings Potential”, which I assume to be the difference between the “Existing” and “Optimal”, but the “Optimal” configuration is not shown for modification 1.

I think, the savings for Modification 1 are supposed to be relative to the Baseline, such that if they had the same inputs, the “Annual Savings Potential” would be Zero. And there should not be an "optimization" for Modification 1

OR
Show the “Optimal” for Modification 1 in the summary (like in PSAT08), so we at least know what the system achieving savings looks like

![picture1](https://user-images.githubusercontent.com/25389736/27244482-b3de2ecc-52b4-11e7-8860-de4e2475ce2d.png)

**Comment by rmroot** [comment]
From Daryl

"The savings are relative to the values of the input parameters.  If two conditions have the same input values you should get the same result.  The graphic that shows results for Baseline and Modification 1 is correct and the value for Modification 1 is correct at $9,582.71, although I would round to $9,583 since our calculations are not precise enough to get into cents."

I will make the rounding adjustment but keep the value as is.

**Comment by rmroot** [comment]
After further discussion between Daryl and Kristina I believe this issue should be re-opened. More details to come.
