### ISSUE TITLE
Motor Inventory: Inventory Summary

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3846]
Setup motor inventory summary page

**Comment by koay9f** [comment]
looks good on big monitor, but not good on my laptop.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/92e83a1d-e565-4777-be95-d63275fd5f5e)

Can we make it so that there is a minimum y-size for the bar chart and put a scroll bar on the whole page?
the x-direction we can probably let sort itself out.
I'm not really sure what to suggest for the pie.  I guess also just a minimum y-size?
