### ISSUE TITLE
Plotly Update Motor Performance

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#3897]

**Comment by koay9f** [comment]
sorry to be picky - can we get the legend to be horizontal aligned on the bottom?  It takes up a lot of room where it is

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a742ff14-1d78-4265-aa6b-50b8400a2b30)![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1bfff74a-6a1c-4413-8a33-2745e1764e55)

Red circles - that should be 40%: no `1` at the end (I don't even know why it is there...) and needs a x100 

This might be too much - when you have the "dots" box (green arrow) could the other box (blue arrow) go away?
Or, since you have the black box at the bottom, We don't really need the special one for the dots (green).
