### ISSUE TITLE
WasteWater: Report Rollup

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4048]
Add waste water to report rollup.

Need individual reports and waste water summary

**Comment by rmroot** [comment]
verify printing looks good

**Comment by rmroot** [comment]
Missed setup not done for waste water reports. Moving back

**Comment by koay9f** [comment]
when I click on the summary at the top "click for details" just get the transparent black screen. nothing there.

Same for any of the top bar...

Printing also weird.  If I click Print, nothing happens. if I nav away and come back, the menu is there

printed report is okay.  I think only the roll up is in it (since the report isn't working that makes sense...)
