### ISSUE TITLE
Opening TH Integration

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4445]

**Comment by koay9f** [comment]
This is probably going to be the same for the other TH assessment calcs:

Energy Source Type: change the last two entries to "Electricity" and "Steam" (instead of electrotechnology and steam-based)
Fuel Cost should be based on the value in "Facility Basics" (see compressed air reduction calc)

Label for Available Heat is missing for NG & Other Fuel
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/32ea7cd7-1519-4b8a-a824-39bb8a8ef375)

Electricity:
it looks like if you switch between fuel and electrotech, the final result (energy / hour) is not undergoing the unit conversion from {suite unit, mmbtu?} to kWh, so it is giving incorrect results.
TEST: put in numbers for size of holes. have available heat = 100%, have fuel cost = $5 and electricity cost = $0.018.
Then the COST results should be the same (the energy number will be different)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7605ca5a-ce71-4404-861a-225ce59b2b25)


Energy Source Switching:
Switching energy source is correctly reflected in treasure chest!!!! (honestly a bit surprised this worked the first time)
