### ISSUE TITLE
CO2 Emissions US average default

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5163]
After all CO2 implementation are complete...

Coordinate with Kristina to decide best implementation:

1. How do we want to populate US avg emissions when there is a new assessment/empty CO2 output? i.e. blue link button, auto populate, etc....... Mark also pointed out we could also pull zip from facility info
2. Implement in all CO2 locations (Break this into smaller issues as you go)

We're currently taking the value from global settings if it exists, otherwise populating nothing for electricity energy, natural gas for fuel energy

**Comment by koay9f** [comment]
US Average 401.07 0.034 0.005

**Comment by koay9f** [comment]
I think we were still wanting an error to give the U.S. default. 
if the input = a number in the db --> return that number, else return U.S. default.
Validation - no value / number not in the db is a yellow warning with this message 
`Enter a valid zip code to find your eGRID subregion, otherwise displaying U.S. Average`

**Comment by nbintertech** [comment]
@rhernandez-intertech we're going to hold off on changing this until other CO2 pieces are wrapped and confirmed.

**Comment by rmroot** [comment]
I am just going to implement this along with issue for updating examples

**Comment by koay9f** [comment]
Not implemented in process heating
