### ISSUE TITLE
Rollup and EAF

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5283]
Need to confirm this works with changes made in 5267. 

On the rollup, we'll only show "Chemical Heat" fuel energy/cost vs "Electricity" energy/cost, even though the PHAST report section displays coal, electrode, other.  In the new pie charts the chemical heat will be summed into 'Fuel"

**Comment by koay9f** [comment]
not sure what, but something isn't right

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/47b1333e-1188-4c81-9b3f-4ee137e41a66)

I think the fuel/chemcial is being sent as hourly instead of annual, maybe?

Electro
Fuel = 119.44 kW = 0.5mmbtu
Electric = 607.08 kW = 2.07 mmbtu
EAF
chemical = 1536.28 kW = 5.25mmbtu
electric = 6000 kW = 20.47mmbtu

[https://app.zenhub.com/files/80439269/546e84a7-d420-416c-bff8-48c485567b39/download](https://app.zenhub.com/files/80439269/546e84a7-d420-416c-bff8-48c485567b39/download)

**Comment by nbintertech** [comment]
Should this chart show annual or hourly results? We're presenting annual in the other assessments (pumps and fans at  least)

I have implemented as annual:
- Annual electricity use -->  52,560,000 kWh = 6000 * 8760 
- rollup annual electricity use --> 179,341=   convert 52,560,000 from energy result unit to rollup unit (kWh to MMBtu)

**Comment by koay9f** [comment]
SO CLOSE!

It looks like the graph is assuming something about the units that it is getting the data in (probably that it is in MMBTU).
If you change the rollup report units to something else things get weird:
Process Heating Roll up units = MMBTU - looks good
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0caf28d4-2a55-4bac-abd0-c2469e750c33)
Process Heating Roll up units = kcal
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/46533b3d-44da-4b1a-9a54-25092a41742f)
Assessment in metric
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ffe064f1-7450-4aa4-8be5-0cba664a3cdd)

This is also a probelm with the first graph (Annual Energy Use)
Process HEating Unit = MMBTU, assessment in imperial
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/afa59a18-5f33-46fe-bd24-0f132bb2d681)
Process Heating Unit = MWh
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8166aae5-c353-4137-9978-578a1f535ed8)
Roll up unit = MWh, Process HEating Unit = MMBTU
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7c25e945-d4f1-47e0-b1e4-175eee2b26e3)
