### ISSUE TITLE
Google tracking enhancements

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5631]
Errors occur in private browsing with cookies blocked from the google tracking data

Enhance tracking data

Add opt-out option

**Comment by nbintertech** [comment]
I think this case is covered by below pop up added from previous analytics issue...
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/f2324135-6f67-483f-8ee8-d4f09c70d794)

Don't really see a way to opt out of this since we use IDB for everything and this effectively kill that.
