### ISSUE TITLE
Help text for disabled fields

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5655]
It would be nice if we could still have help text for disabled fields, so users would know why it is disabled
Currently can't do b/c help text is dependent on clicking. 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/da50df8f-b459-411f-b564-cce2983365eb)

**Comment by JL102** [comment]
Help text does not show in this case because it is tied to the inputs' `focus` events, which do not fire when an input is disabled.
Since the app is monstrous, and the way help text is shown is well established, the optimal solution would not be to modify the way help text is shown (for example, as an onClick handler for specific inputs/labels which might sometimes be disabled). Rather, we should add a small script which forces the `focus` event to fire in the case that it (or its label) is clicked while it is disabled.

**Comment by koay9f** [comment]
Why is this still in needs review and not in needs verification? Is it in develop?
