### ISSUE TITLE
TH - PPT Improvements 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#6018]
- Add slide for "Best Practices" 
- Add slide for "Other Opportunities Not Evaluated" 
- Add slide with savings gauges 
- Add carbon savings 

- Reduce the number of repetitive slides where possible

**Comment by koay9f** [comment]
Should not delay release:
Best Practices & Other Opportunities -
Go ahead and have a text box for the page. Have it be bulleted list with text 
"* Outline key best practices identifed in Treasure Hunt here"
and 
"* Outline any major opportunities identified, but not evaluated here"

Savings gauges were not in 

I like the carbon donut  - maybe cut pie and combine the table slide with the donut (like teams)

maybe add cost donut also? (utility could get messy, maybe add electricty & NG if easy, otherwise just skip - maybe put just those two donuts on "Energy Utiltiy Usage & Cost" slide, skip the pie :D)

**Comment by rhernandez-intertech** [comment]
replacing gauges with donuts
