### ISSUE TITLE
undefined property in Data Exploration after uploading files

### ISSUE THREAD

**Issue by kaichen127** [ORNL-AMO/AMO-Tools-Desktop#6362]
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/e6cef594-aad4-4a07-bd5d-7f90f9303198)

After importing via "Upload Files" , after clicking "Next" a bunch of times without filling in any fields, I get a console error - here are the csv files I used to create the error
[https://app.zenhub.com/files/80439269/f3a26079-abd0-42e8-bd6d-a14ac0839609/download](https://app.zenhub.com/files/80439269/f3a26079-abd0-42e8-bd6d-a14ac0839609/download)

**Comment by nbintertech** [comment]
- Prevent app errors/crash if user next's-thru refine data and map date/time tabs

**Comment by koay9f** [comment]
This could be a continuation of the slide bar issue (#6507), but I just "next-thru'ed" and got errors:
If you think it is fixed with the fixing of the slide bar, just move it back over :)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--968f11a36fd20b28af7ba06bffe0fb6268313708/image.png)
